import { escapeHTML, origin } from './content-pages';
import { renderCipherResearch } from './cipher-research';

export const cipherSource = 'https://github.com/ChaseHendrick/Undeciphered-Texts';
export const cipherLabPage = {
  route: '/cipher-lab/',
  title: 'Cipher Lab: Cipher Solvers & Research Notes | Hendrick Research',
  description: 'Try classical cipher solvers and Bob the Neural Net. Explore sourced research notes on undeciphered scripts and unsolved historical ciphers.',
  schema: {
    '@type': 'WebPage',
    about: [{ '@type': 'Thing', name: 'Cryptanalysis' }, { '@type': 'Thing', name: 'Undeciphered writing systems' }, { '@type': 'Thing', name: 'Historical ciphers' }],
    mainEntity: {
      '@type': 'WebApplication', name: 'Cipher Lab',
      applicationCategory: 'EducationalApplication', operatingSystem: 'Web browser',
      url: origin + '/cipher-lab/', isAccessibleForFree: true,
      description: 'A browser workbench for bounded classical cipher searches and cipher-family classification.',
      featureList: ['Caesar and rail-fence search', 'Crib-constrained inference', 'Ten solver personas', 'Cipher-family classification', 'Local JSON report export', 'Source-linked research notes'],
      author: {'@type': 'Person', name: 'Chase Hendrick'},
      isBasedOn: {'@type': 'SoftwareSourceCode', name: 'Undeciphered Texts', codeRepository: cipherSource},
    },
    breadcrumb: {'@type': 'BreadcrumbList', itemListElement: [
      {'@type': 'ListItem', position: 1, name: 'Hendrick Research', item: origin + '/'},
      {'@type': 'ListItem', position: 2, name: 'Cipher Lab', item: origin + '/cipher-lab/'},
    ]},
  },
};

export const cipherExamples = [
  {name: 'Caesar control', tool: 'normal-man', text: 'CQNURKAJARJWYUJLNMCQNBNJUNMUNCCNAKNBRMNCQNVJYJWMFJRCNMOXACQNWRPQCCAJRWFQRUNCQNAJRWONUUXWCQNBRUNWCYUJCOXAV', cribs: '', keywords: '',
    note: 'A frozen synthetic control from the repository. No key or plaintext is supplied to the search.'},
  {name: 'Redefence example', tool: 'cartographer', text: 'IIWRILCPECLFDHVAEIR', cribs: '', keywords: '',
    note: 'A published American Cryptogram Association control. Short text can rank a wrong reading first; inspect the alternatives.', source: 'https://www.cryptogram.org/downloads/aca.info/ciphers/Redefence.pdf'},
  {name: 'Vigenere with a clue', tool: 'inheritance', text: 'LXFOPVEFRNHR', cribs: '0:ATTACK', keywords: 'LEMON, ORANGE',
    note: 'A known-answer teaching example. The supplied clue and keyword guesses constrain the result; this is not an unknown historical solve.'},
] as const;

export const cipherTools = [
  {id: 'normal-man', name: 'Normal Human Man', note: 'Start small: all 26 Caesar shifts and six rail-fence heights. A plain, useful baseline.'},
  {id: 'persona-council', name: 'Solver council', note: 'Connect ten complementary search and review policies under one shared budget. Agreement alone is not proof.'},
  {id: 'emperor', name: 'Emperor', note: 'A systematic classical investigation with a factual ledger and optional neural advice.'},
  {id: 'inheritance', name: 'Inheritance', note: 'Use your keyword guesses, word list and aligned cribs. It needs caller-supplied clues.'},
  {id: 'hallucinogens', name: 'Hallucinogens', note: 'Try finite reversals, rotations and affine combinations. Every candidate must reproduce the ciphertext.'},
  {id: 'pacifist', name: 'Pacifist', note: 'Try the finite affine keys and exact crib checks, without persona vocabulary preferences.'},
  {id: 'detective', name: 'Detective', note: 'Place an unplaced crib and look for repeated-key evidence. Enter the clue in the unplaced crib field.'},
  {id: 'cartographer', name: 'Cartographer', note: 'Explore bounded rail, route, Redefence and rectangular transposition layouts.'},
  {id: 'mechanic', name: 'Mechanic', note: 'Use aligned cribs for progressive keys, autokey recurrences and Hill constraints.'},
  {id: 'adversary', name: 'Adversary', note: 'Look for alternative readings consistent with the same supplied evidence.'},
  {id: 'skeptic', name: 'Skeptic', note: 'Review a proposed reading against reserved cribs or a reference hash. A dry voice, exact checks.'},
  {id: 'hill-inference', name: 'Hill matrix inference', note: 'Infer bounded two-by-two Hill matrices from aligned cribs. A nonempty fitting crib is required.'},
  {id: 'transposition-ensemble', name: 'Transposition ensemble', note: 'Search a finite set of layouts, with explicit completion and exact forward checks.'},
] as const;

export function renderCipherLab(): string {
  const nav = '<a href="/#projects">Projects</a><a href="/games/">Games</a><a href="/music/">Music</a><a href="/cipher-lab/" aria-current="page">Cipher Lab</a><a href="/generative-art/">Art</a><a href="/research/">Research</a><a href="/fibers/">Fibers of Earth</a>';
  const example = cipherExamples[0];
  return `<a class="skip-link" href="#main">Skip to Cipher Lab</a>
    <header class="site-header wrap"><a class="brand" href="/" aria-label="Hendrick Research home"><picture><source srcset="/logo.webp" type="image/webp"/><img src="/logo.png" width="1536" height="1024" alt="Hendrick Research" decoding="async" /></picture></a><nav class="desktop-nav" aria-label="Main navigation">${nav}</nav><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav"><span></span><span></span></button><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden>${nav}</nav></header>
    <main id="main" class="cipher-main wrap">
      <section class="cipher-hero" aria-labelledby="cipher-title"><div><p class="eyebrow">CIPHER LAB / A WORKBENCH FOR THE UNKNOWN</p><h1 id="cipher-title">Cipher Lab<span class="cipher-tagline">Find a method. <em>Follow the evidence.</em></span></h1><p class="cipher-intro">Explore classical ciphers with the solvers from <a href="${cipherSource}" target="_blank" rel="noopener noreferrer">Undeciphered Texts</a>.</p><div class="cipher-hero-links"><a class="text-link" href="#methods">Meet the solvers <span aria-hidden="true">↗</span></a></div></div>
        <figure class="cipher-specimen"><div class="cipher-specimen-top"><span>FIG. 01 / THREE LETTERS APART</span><span aria-hidden="true">+</span></div><div class="cipher-letter-grid" aria-label="A Caesar example maps KHOOR to HELLO">${['K','H','O','O','R'].map((letter,i) => `<div><span class="cipher-index">0${i+1}</span><span class="cipher-letter">${letter}</span><span class="cipher-rule" aria-hidden="true">↓</span><span class="cipher-clear">${'HELLO'[i]}</span></div>`).join('')}</div><figcaption><span>A Caesar shift, made visible.</span><span>One simple method. Many harder questions.</span></figcaption></figure>
      </section>
      <div class="cipher-principles"><span><i class="status-dot"></i> Runs on your device</span><span>Original Python engine</span><span>Candidates with evidence</span></div>
      <section id="workbench" class="cipher-workbench" aria-labelledby="workbench-title"><div class="cipher-section-heading"><div><p class="eyebrow">01 / TRY A READING</p><h2 id="workbench-title">Work the cipher.</h2></div><p>Start with an example,<br />or bring your own transcription.</p></div>
        <noscript><p class="cipher-notice">The workbench needs JavaScript. The <a href="${cipherSource}">Python engine and documentation</a> are also available to run locally.</p></noscript>
        <div class="cipher-example-row" role="group" aria-label="Load a cipher example"><span>Try an example</span>${cipherExamples.map((e,i) => `<button type="button" data-example="${i}"${i===0?' aria-pressed="true"':' aria-pressed="false"'}>${e.name}</button>`).join('')}<button type="button" id="cipher-clear">Clear</button></div>
        <div class="cipher-workspace"><form id="cipher-form"><fieldset id="cipher-fields"><legend class="sr-only">Cipher input and search settings</legend><div class="cipher-mode-tabs" role="tablist" aria-label="Workbench mode"><button type="button" role="tab" id="cipher-mode-search" aria-selected="true" aria-controls="cipher-search-settings">Search for a reading</button><button type="button" role="tab" id="cipher-bob" aria-selected="false" aria-controls="cipher-bob-explainer" tabindex="-1">Identify the family</button></div><label for="cipher-input">1 / Ciphertext <span id="cipher-count">${example.text.length} letters</span></label><textarea id="cipher-input" rows="5" maxlength="4096" spellcheck="false" autocapitalize="characters" aria-describedby="cipher-alphabet">${example.text}</textarea><p id="cipher-alphabet" class="cipher-hint">4 to 512 A-Z letters. Spaces and punctuation are ignored. Digits and other alphabets need a different tool.</p><p id="cipher-example-note" class="cipher-hint">${example.note}</p>
          <div id="cipher-search-settings" role="tabpanel" aria-labelledby="cipher-mode-search"><div class="cipher-select-row"><div><label for="cipher-tool">2 / Solver</label><select id="cipher-tool">${cipherTools.map(t => `<option value="${t.id}">${t.id==='normal-man'?'Quick search':t.id==='persona-council'?'Solver council':t.name}</option>`).join('')}</select></div><div><label for="cipher-budget">Check budget</label><select id="cipher-budget"><option value="2000">2,000 checks</option><option value="5000" selected>5,000 checks</option><option value="10000">10,000 checks</option></select></div></div><p id="cipher-tool-note" class="cipher-hint">${cipherTools[0].note}</p>
          <details class="cipher-clues"><summary><span id="cipher-clue-summary">Add clues (optional)</span><span aria-hidden="true">+</span></summary><div class="cipher-clue-content"><p class="cipher-hint">The fields shown here apply to this solver. Your other clues are kept when you switch methods.</p>
            <div data-clue-group="fitting"><label for="cipher-cribs">Known words and positions</label><textarea id="cipher-cribs" rows="2" placeholder="0:ATTACK" maxlength="1024" spellcheck="false" aria-describedby="cipher-crib-hint"></textarea><p id="cipher-crib-hint" class="cipher-hint">A crib is a word you expect in the plaintext. Enter one offset:word per line. Positions start at zero after removing spaces and punctuation.</p></div>
            <div data-clue-group="unplaced" hidden><label for="cipher-unplaced">Known word, unknown position</label><input id="cipher-unplaced" maxlength="128" placeholder="A word to look for" spellcheck="false"/></div>
            <div data-clue-group="keywords" hidden><label for="cipher-keywords">Possible keywords</label><input id="cipher-keywords" maxlength="1000" placeholder="LEMON, ORANGE" spellcheck="false"/><p class="cipher-hint">Separate guesses with commas or spaces.</p></div>
            <div data-clue-group="lexicon" hidden><label for="cipher-lexicon">Possible plaintext words</label><textarea id="cipher-lexicon" rows="2" maxlength="2000" placeholder="One word per line, or separated by commas" spellcheck="false"></textarea></div>
            <div data-clue-group="proposal" hidden><label for="cipher-proposal">Reading to review</label><textarea id="cipher-proposal" rows="2" maxlength="4096" spellcheck="false" placeholder="Your proposed plaintext"></textarea><p class="cipher-hint">Use the same number of normalized letters as the ciphertext.</p></div>
            <div data-clue-group="verification" hidden><details class="cipher-verification"><summary>Check independent evidence</summary><p class="cipher-hint">Keep these clues out of fitting. The council's Skeptic uses them only to review the final shortlist.</p><label for="cipher-reserved">Reserved words and positions</label><textarea id="cipher-reserved" rows="2" maxlength="1024" placeholder="offset:word" spellcheck="false"></textarea><label for="cipher-reference">Reference plaintext SHA-256</label><input id="cipher-reference" maxlength="64" pattern="[a-fA-F0-9]{64}" placeholder="Optional exact reference hash" spellcheck="false"/><p class="cipher-hint">Reserved and fitting positions must be separate. A reference hash checks agreement with your reference; its authenticity needs separate evidence.</p></details></div>
          </div></details>
          </div><div id="cipher-bob-explainer" role="tabpanel" aria-labelledby="cipher-bob" hidden><h3>Ask Bob the Neural Net.</h3><p>Bob suggests known cipher families so you can choose a search method. It needs at least 16 letters. A family probability is not a plaintext confidence score.</p></div><div class="cipher-actions"><button class="button button-dark" id="cipher-run" type="submit">Run solver <span aria-hidden="true">↗</span></button><span id="cipher-action-note">A bounded search with explicit checks.</span></div></fieldset><button id="cipher-cancel" type="button" class="text-link" hidden>Cancel current run</button><p class="cipher-hint cipher-runtime-note">First run loads the local engine. Your ciphertext stays on your device. <a href="#cipher-engine-details">How it runs</a>.</p></form>
          <section class="cipher-output" aria-labelledby="cipher-output-title" aria-busy="false"><div class="cipher-output-top"><p class="eyebrow" id="cipher-output-title">02 / EVIDENCE & CANDIDATES</p><span id="cipher-state">Ready for input</span></div><p id="cipher-status" role="status" aria-live="polite">Load an example or paste your text, choose a solver, then run. The engine loads only when you need it.</p><div id="cipher-results" tabindex="0" aria-label="Cipher results"><div class="cipher-empty"><span class="cipher-empty-mark" aria-hidden="true">?</span><h3>A reading starts with a check.</h3><p>Candidate plaintexts, forward checks and search limits will appear here. An English-looking answer still needs independent evidence.</p></div></div><div class="cipher-export" hidden><button id="cipher-download" type="button" class="text-link">Download JSON report ↓</button><button id="cipher-copy" type="button" class="text-link">Copy JSON</button></div><details id="cipher-raw" hidden><summary>Inspect the complete report</summary><pre id="cipher-json"></pre></details></section>
        </div>
      </section>
      <details id="methods" class="cipher-methods"><summary class="cipher-method-summary"><span>Explore the ten solver personas</span><span aria-hidden="true">+</span></summary><section aria-labelledby="methods-title"><div class="cipher-section-heading"><div><p class="eyebrow">03 / COMPLEMENTARY METHODS</p><h2 id="methods-title">Different ways into the same question.</h2></div><p>Ten research personas.<br />One standard for correctness.</p></div><div class="cipher-method-grid">${cipherTools.slice(0,11).filter(t=>t.id!=='persona-council').map((t,i) => `<article><p class="eyebrow">${String(i+1).padStart(2,'0')} / SEARCH & REVIEW</p><h3>${escapeHTML(t.name)}</h3><p>${escapeHTML(t.note)}</p><button class="text-link" type="button" data-policy="${t.id}">Try this policy <span aria-hidden="true">↗</span></button></article>`).join('')}</div></section></details>
      <section class="cipher-explanation" aria-labelledby="cipher-evidence-title"><div><p class="eyebrow">04 / KEEP THE EVIDENCE</p><h2 id="cipher-evidence-title">A candidate is<br /><em>the beginning.</em></h2></div><div><h3>What can this cipher solver do?</h3><p>Try bounded Caesar, affine and transposition searches. Supply cribs for repeated-key, autokey and Hill inference. Connect the research personas in a shared council, then inspect their assumptions, checks and candidate witnesses.</p><h3>What does Bob the Neural Net do?</h3><p>Bob ranks known cipher families from statistical and cryptanalytic features. A family suggestion helps choose the next method; it does not establish a key or decrypt the text. Its model and benchmark provenance ship with the workbench.</p><h3>When is a cipher actually solved?</h3><p>A candidate must account for the ciphertext and survive evidence that was not used to fit it. A high language score, several agreeing personas, or an exact fit to your own clue is not independent proof. The engine keeps unresolved historical claims unresolved.</p><h3>Where can I inspect the code?</h3><p>This workbench runs a pinned snapshot of the open-source Python engine. The repository includes source-backed controls, tests, certificates and a structured case workflow for unsolved ciphers.</p><div class="cipher-source-links"><a class="text-link" href="${cipherSource}" target="_blank" rel="noopener noreferrer">Source code ↗</a><a class="text-link" href="${cipherSource}/blob/main/docs/WORKFLOW.md" target="_blank" rel="noopener noreferrer">Research workflow ↗</a><a class="text-link" href="${cipherSource}/blob/main/docs/verification-certificates.md" target="_blank" rel="noopener noreferrer">Verification certificates ↗</a></div><details id="cipher-engine-details" class="cipher-engine-details"><summary>Engine and model provenance</summary><p class="cipher-hint">The first run downloads Python and NumPy from the pinned Pyodide CDN, then executes the original engine in a worker on your device. Network access is needed for those initial files. Inputs and results are not uploaded to a solver service.</p><p id="cipher-provenance" class="cipher-hint">The exact engine snapshot and file hashes are listed in the <a href="/cipher-lab/manifest.json">build manifest</a>.</p></details></div></section>
      ${renderCipherResearch()}
    </main><footer class="cipher-footer wrap"><a href="/">Hendrick Research</a><p>Research. Software. Possibility.</p><a href="${cipherSource}" target="_blank" rel="noopener noreferrer">Undeciphered Texts ↗</a></footer>`;
}
