import data from './siege-data.json';
import type {ContentPage} from './content-pages';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const origin='https://www.hendrickresearch.com';
const route=(id:string)=>`/sieges/${id}/`;
const play=(id:string)=>`/play/siegeworks/?siege=${id}`;
const image=(id:string)=>`/sieges/previews/${id}.png`;
const link=(url:string,label:string)=>`<a class="editorial-link" href="${escape(url)}">${escape(label)} <span aria-hidden="true">↗</span></a>`;
const observations:Record<string,string[]>={
 masada:['Follow a basket carrier from the supply camp onto the natural western spur. The crew’s loading, hauling, depositing, and return cycles determine how quickly the ramp grows.', 'Use Works to inspect the construction front. New material changes the approach height; the timber tower waits until the works are ready before advancing up the slope.', 'Use City to inspect the casemate walls and plateau buildings. Defenders patrol the battlements and launch simplified projectiles toward the approaching works.'],
 alesia:['The inner defense faces the hilltop settlement; the outer defense faces the surrounding countryside. Work crews distribute their tasks around both circuits.', 'Roman patrols move between the lines. After the construction phase, a relief force approaches the outer perimeter while the defenders continue watching from the settlement.', 'Use Overview to compare the two circuits, then zoom in on stakes, earthworks, and the people carrying supplies. The model compresses a much larger conflict landscape.'],
 jerusalem:['Start at the supply camp and follow workers carrying material toward the assault approach. The terrain rises into a city with successive walls and closely packed buildings.', 'The tower moves only when the approach is ready. Watch projectiles under gravity and inspect how the front wall responds to repeated impacts.', 'The city and monumental buildings are schematic. Read the historical sources alongside the model, especially when comparing the scene with Josephus’s narrative.'],
 tyre:['Watch the stone causeway emerge toward the island city. The construction cells track accumulated material, and the workers walk on the changing surface.', 'Ships move around the approach while waves and sails animate. These ships use simple controlled paths; the scene does not attempt to solve naval warfare or coastal sediment transport.', 'Compare the camp view on the mainland with the city view on the island. Once the causeway is ready, the tower advances along the new route.'],
 constantinople:['Workers prepare the artillery approach while supply carriers move forward from camp. The scene includes a compressed section of the layered land walls.', 'Choose Advance works to reach the artillery phase quickly, or watch construction unfold. Cannonballs follow physical trajectories and collide with terrain and walls.', 'Inspect the front wall as repeated hits batter its central section. The miniature’s projectile speed and damage are illustrative, not a measured reconstruction of Ottoman artillery.'],
 candia:['Digging crews extend a zigzag approach toward the bastioned city. Finished cells lower the trench floor and build up the protective edges.', 'After the works are ready, the cannon moves into its firing position. Watch impacts, dust, and the defenders’ responses around the front wall.', 'Candia was a long Ottoman siege of a Venetian city. This model isolates the engineering of an approach; it does not compress the full historical campaign into a claimed chronology.'],
};
function cards(exclude?:string){return data.filter(s=>s.id!==exclude).map(s=>`<article class="siege-guide-card"><a href="${route(s.id)}"><img src="${image(s.id)}" alt="${escape(`${s.name} siege, an original procedural miniature in Siegeworks`)}" width="1440" height="1000" loading="lazy" decoding="async"/><p class="eyebrow">${escape(s.faction)} / ${escape(s.date)}</p><h3>${escape(s.name)}</h3></a><p>${escape(s.description)}</p><div class="editorial-actions">${link(play(s.id),`Play ${s.name}`)}${link(route(s.id),'Read the field guide')}</div></article>`).join('');}
export function siegePages():ContentPage[]{
 const collection:ContentPage={route:'/sieges/',title:'Historical Siege Simulations: Roman Sieges & More | Siegeworks',description:'Play six historical siege simulations in your browser: Masada, Alesia, Jerusalem, Tyre, Constantinople, and Candia. Explore animated workers, engineering, and physics.',image:image('masada'),body:`<section class="editorial-hero"><p class="eyebrow">HISTORY / ENGINEERING / PLAY</p><h1>Historical sieges.<br /><em>Living miniatures.</em></h1><p class="editorial-intro">Six browser simulations of historical siege engineering, from Roman ramps and double defenses to an island causeway and the age of cannon. Watch little people build, carry, patrol, and react in original miniature landscapes.</p>${link('/play/siegeworks/','Play the collection')}</section><p class="editorial-note">These scenes are schematic historical visualizations. Geometry, population, construction speed, and combat are simplified. Each field guide links to historical sources and states the model’s limits.</p><section class="editorial-section"><h2>Choose a siege.</h2><div class="game-collection siege-guide-grid">${cards()}</div></section><section class="editorial-section"><h2>Watch, inspect, and intervene.</h2><p class="section-intro">Crews load baskets, haul material, lay foundations, or dig the approach. Workers and soldiers have visible jobs and conditions. Pick them up, drop them, or flick to throw them into a world with gravity and collisions. People recover and return to their tasks.</p><p class="section-intro">All six worlds are free to play in a modern browser with WebGL. Mouse and touch controls are supported. Each siege saves separately in this browser, and time stops when the page is closed. Use dim surroundings or full screen for more room.</p>${link('/simulations/','Explore other playable simulations')}</section>`,schema:{'@type':'CollectionPage',mainEntity:{'@type':'ItemList',numberOfItems:data.length,itemListElement:data.map((s,i)=>({'@type':'ListItem',position:i+1,url:origin+route(s.id),name:s.name+' siege simulation'}))}}};
 const pages=data.map(s=>{const title=`${s.name} Siege Simulation: ${s.work} | Siegeworks`,body=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/sieges/">Historical sieges</a><span aria-hidden="true">/</span><span>${escape(s.name)}</span></nav><section class="editorial-hero"><p class="eyebrow">${escape(s.faction.toUpperCase())} / ${escape(s.region.toUpperCase())} / ${escape(s.date)}</p><h1>${escape(s.name)}.<br /><em>${escape(s.work)}.</em></h1><p class="editorial-intro">${escape(s.description)}</p>${link(play(s.id),`Play the ${s.name} siege simulation`)}</section><figure class="method-feature siege-guide-feature"><img src="${image(s.id)}" alt="${escape(`${s.name} siege simulation in Siegeworks: ${s.work.toLowerCase()} and a miniature ${s.region} landscape`)}" width="1440" height="1000" fetchpriority="high" decoding="async"/><figcaption>Original procedural miniature · Simplified landscape and construction</figcaption></figure><section class="editorial-section"><h2>What to watch.</h2>${observations[s.id].map(p=>`<p class="section-intro">${escape(p)}</p>`).join('')}</section><section class="editorial-section"><h2>The historical setting.</h2><p class="section-intro">${escape(s.fact)}</p><h3>How the model simplifies it</h3><p class="section-intro">${escape(s.limit)}</p><p class="editorial-note">Three.js renders the scene, while cannon-es handles dynamic bodies, gravity, collisions, pickup constraints, and projectiles. Workers follow local job routines. Siege engines and ships use controlled movement. This is a playable engineering visualization, not an archaeological survey or a calibrated battle model.</p></section><section class="editorial-section"><h2>Play in your browser.</h2><p class="section-intro">Construction begins automatically. Choose Overview, Works, City, or Camp to move closer. Drag to orbit and scroll or pinch to zoom. Click a person to inspect their job, then choose Follow this person if you want to stay with them.</p><p class="section-intro">Grab & toss lifts workers and soldiers. Release slowly to drop or flick to throw. Shockwave knocks nearby people off balance. Space pauses; 1×, 4×, and 12× change the simulation speed. Advance works moves you to the later phase. Progress is saved separately for each siege in this browser.</p>${link(play(s.id),`Open ${s.name}`)}</section><section class="editorial-section"><h2>Sources and further reading.</h2><div class="editorial-actions">${s.sources.map(([label,url])=>link(url,label)).join('')}</div><p class="editorial-note">These links support the historical context. The miniature’s geometry, agents, and physical parameters are original simplified implementations.</p></section><section class="editorial-section"><h2>Explore another siege.</h2><div class="game-collection siege-guide-grid">${cards(s.id)}</div></section>`;
 return{route:route(s.id),title,description:`Play the ${s.name} siege simulation (${s.date}) in your browser. Watch ${s.work.toLowerCase()}, animated work crews, soldiers, and physical interactions.`,image:image(s.id),body,schema:{'@type':'WebPage',about:{'@type':'Thing',name:`Siege of ${s.name}`,description:s.fact},isPartOf:{'@type':'CollectionPage',name:'Historical siege simulations',url:origin+'/sieges/'},mainEntity:{'@type':['VideoGame','WebApplication'],name:`Siegeworks: ${s.name}`,description:s.description,genre:['Historical simulation','Physics sandbox'],url:origin+play(s.id),operatingSystem:'Web browser',applicationCategory:'GameApplication',isAccessibleForFree:true}}} satisfies ContentPage;});
 return[collection,...pages];
}
